version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql